environment:
  matrix:
    - nodejs_version: '11'
    - nodejs_version: '10'
    - nodejs_version: '9'
    - nodejs_version: '8'
    - nodejs_version: '6'
install:
  - ps: >-
      if ($env:nodejs_version -eq "11") {
        Install-Product node $env:nodejs_version x64
      } else {
        Install-Product node $env:nodejs_version
      }
  ps: 
  - set PATH=%APPDATA%\npm;%PATH%
  - ps: >-
      if ($env:nodejs_version -eq "6") {
        npm i -g npx
      }
  - npm install
matrix:
  fast_finish: false
build: off
shallow_clone: true
test_script:
  - node --version
  - npm --version
  - npx --version
  - npm run test-with-no-coverage-check
  # Update npm to check that audit analyzer is then (still) active
  - npm i -g npm@latest
  - node --version
  - npm --version
  - npx --version
  - npm test
cache:
  - '%APPDATA%\npm-cache'